import type { Metadata } from "next";
import "./globals.css";
import { ChatProvider } from "@/context/chatContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChatProvider>
        {children}
        </ChatProvider>
      </body>
    </html>
  );
}
